apiVersion: telemetry.intel.com/v1alpha1
kind: TASPolicy
metadata:
  name: power-policy
spec:
  strategies:
    deschedule:
      rules:
      - metricname: collectd_package_0_power_power
        operator: GreaterThan
        target: 33
    dontschedule:
      rules:
      - metricname: collectd_package_0_power_power
        operator: GreaterThan
        target: 32
