apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secondary-scheduler-operator
  template:
    metadata:
      labels:
        name: secondary-scheduler-operator
    spec:
      containers:
        - name: secondary-scheduler-operator
          image: quay.io/ferossi/secondary-scheduler-operator:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - secondary-scheduler-operator
          args:
          - "operator"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "secondary-scheduler-operator"
      serviceAccountName: secondary-scheduler-operator
      serviceAccount: secondary-scheduler-operator
