apiVersion: v1
kind: Service
metadata:
  name: telemetry-service
  namespace: telemetry
  labels:
    app: collectd
spec:
  selector:
    app: collectd
  type: ClusterIP
  ports:
    - port: 9001
      name: exporter
    - port: 9103
      name: http-collectd
